name: Deploy Static Site

on:
  push:
    branches:
      - main  # Replace with your main branch name
  pull_request:
    branches:
      - main  # Replace with your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest  # Choose your desired runner environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies  # Replace with actual build commands if needed
      run: |
        # Example: If you use npm/yarn for building
        npm install  # or yarn install
        npm run build  # or yarn build

    - name: Deploy to GitHub Pages  # Example for deploying to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Replace with your build output directory
        user_name: GitHub Actions
        user_email: actions@users.noreply.github.com
        publish_branch: gh-pages  # Replace with your GitHub Pages branch

    # Add more steps as needed for additional deployment tasks or notifications
